name: MLflow CI Workflow

on:
  push:
    paths:
      - 'MLProject/**'
  workflow_dispatch:

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-activate-base: false
        activate-environment: mlflow-env
        environment-file: MLProject/conda.yaml
        python-version: 3.10
        auto-update-conda: true

    - name: Confirm Conda Environment
      run: conda info --envs

    - name: Run MLflow project
      run: |
        mlflow run MLProject -P data_path=MLProject/telco_churn_preprocessing/telco_churn_preprocessed.xlsx
