name: MLflow CI Workflow

on:
  push:
    paths:
      - 'MLProject/**'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-activate-base: false
        activate-environment: mlflow-env
        environment-file: MLProject/conda.yaml
        auto-update-conda: true
        use-only-tar-bz2: true

    - name: Verify conda environment
      run: conda info --envs

    - name: Copy dataset into MLProject folder
      run: cp MLProject/telco_churn_preprocessing/telco_churn_preprocessed.xlsx MLProject/telco_churn_preprocessed.xlsx

    - name: Run MLflow project
      shell: bash -l {0}
      run: |
        conda activate mlflow-env
        mlflow run MLProject -P data_path=telco_churn_preprocessed.xlsx

    - name: Upload model artifact
      uses: actions/upload-artifact@v4
      with:
        name: churn-model
        path: MLProject/mlruns

    - name: Docker login
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/mlflow-churn:latest .

    - name: Push Docker image to Docker Hub
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/mlflow-churn:latest

