name: MLflow CI Workflow

on:
  push:
    paths:
      - 'MLProject/**'
  workflow_dispatch:

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Conda and Python
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: mlflow-env
        environment-file: MLProject/conda.yaml
        python-version: 3.10
        auto-activate-base: false

    - name: Install MLflow
      run: |
        conda install pip
        pip install mlflow

    - name: Run MLflow project
      run: |
        mlflow run MLProject -P data_path=telco_churn_preprocessing/telco_churn_preprocessed.xlsx
